"""
Causal model definitions for the task.
"""

from causalab.causal.causal_model import CausalModel
from causalab.causal.trace import Mechanism, input_var
from .templates import TEMPLATES, fill_template
from .config import TASK_NAME, FOOS, BARS

# For single-template tasks, use a module constant (NOT a causal variable).
# Only include template as an input_var when the task has multiple templates.
TEMPLATE = TEMPLATES[0]

# TODO: implement variables, values, parents, mechanisms
# the variables "raw_input" and "raw_output" should both be strings
# Some variables are conceptually best expressed as lists or tuples,
# but the causal model implementation requires separating these into
# individual scalar variables with _{i} suffixes (e.g., choice_0, choice_1).
# Avoid creating compound/aggregate variables.

values = {
    "foo": FOOS,
    "bar": BARS,
    "raw_input": None,  # Generated from template
    "raw_output": None,  # Generated by model
}

# Define mechanisms using the new Mechanism API
mechanisms = {
    # Input variables (no parents)
    "foo": input_var(FOOS),
    "bar": input_var(BARS),
    # Computed variables
    "raw_input": Mechanism(
        parents=["foo", "bar"],
        compute=lambda t: fill_template(TEMPLATE, t["foo"], t["bar"]),
    ),
    "raw_output": Mechanism(
        parents=["raw_input"],
        compute=lambda t: "",  # Placeholder - will be filled by model
    ),
}

causal_model = CausalModel(mechanisms, values, id=TASK_NAME)
