"""Session-local analysis `{{ANALYSIS_NAME}}`.

Generated by `/setup-analyses`. See set_up_analysis.md alongside this file for the
spec; see ARCHITECTURE.md §3 for the layering rules this module respects.
"""

from .main import main

__all__ = ["main"]
