# @package _global_
defaults:
- /base
- /task: natural_domains_arithmetic_weekdays
- /model: llama31_8b   # llama32_1b_instruct cannot solve this task
- /analysis/baseline
- _self_
task:
  target_variable: result
  enumerate_all: true # Enumerate all examples in the training set, test = train
