"""Configuration for the graph_walk task."""

from __future__ import annotations

from dataclasses import dataclass, field

TASK_NAME = "graph_walk"

# Common English nouns likely to be single tokens across tokenizers.
# Short nouns (3-4 letters) are reliably single tokens on most BPE vocabularies.
# Validated at runtime against the actual model's tokenizer — the experiment
# will error if any are multi-token.
#
# Shuffled (seed=42) to avoid alphabetical clustering of starting letters
# when taking a prefix of the list for smaller graphs.
DEFAULT_CONCEPTS = [
    "time",
    "lot",
    "hint",
    "film",
    "mind",
    "den",
    "deer",
    "rain",
    "size",
    "plot",
    "law",
    "wife",
    "jury",
    "hip",
    "tab",
    "star",
    "back",
    "toy",
    "joy",
    "eye",
    "salt",
    "ball",
    "corn",
    "hall",
    "home",
    "term",
    "goal",
    "art",
    "road",
    "cup",
    "copy",
    "dock",
    "fish",
    "rule",
    "lid",
    "wire",
    "folk",
    "hand",
    "boat",
    "jack",
    "pub",
    "pass",
    "jet",
    "trip",
    "burn",
    "heat",
    "tin",
    "port",
    "walk",
    "vine",
    "mat",
    "cook",
    "bond",
    "ink",
    "king",
    "name",
    "seat",
    "loan",
    "farm",
    "sock",
    "lane",
    "disc",
    "mint",
    "spin",
    "sale",
    "loss",
    "bear",
    "gang",
    "wall",
    "ward",
    "mask",
    "mob",
    "mass",
    "fly",
    "job",
    "beam",
    "roll",
    "tone",
    "lord",
    "town",
    "rod",
    "raid",
    "key",
    "net",
    "suit",
    "book",
    "hope",
    "lady",
    "root",
    "horn",
    "sun",
    "sin",
    "end",
    "work",
    "jaw",
    "spy",
    "gun",
    "gear",
    "rim",
    "cost",
    "ford",
    "part",
    "nut",
    "sand",
    "news",
    "flag",
    "web",
    "talk",
    "plan",
    "pace",
    "unit",
    "ear",
    "mess",
    "dot",
    "list",
    "cab",
    "lab",
    "maze",
    "path",
    "pipe",
    "bull",
    "cake",
    "ski",
    "luck",
    "tile",
    "leg",
    "pile",
    "spot",
    "pod",
    "vest",
    "oil",
    "fan",
    "desk",
    "base",
    "risk",
    "fork",
    "bed",
    "jam",
    "ship",
    "sky",
    "hour",
    "hat",
    "rib",
    "lake",
    "wish",
    "cow",
    "oven",
    "code",
    "chip",
    "rest",
    "hen",
    "sort",
    "word",
    "sole",
    "rank",
    "rice",
    "duck",
    "shot",
    "fund",
    "snow",
    "hood",
    "fort",
    "pay",
    "sign",
    "team",
    "wave",
    "tea",
    "iron",
    "tar",
    "tape",
    "soap",
    "pig",
    "wing",
    "chin",
    "ant",
    "year",
    "bone",
    "gap",
    "pet",
    "camp",
    "case",
    "peak",
    "dust",
    "step",
    "kid",
    "coat",
    "boss",
    "pad",
    "cube",
    "bit",
    "roof",
    "node",
    "tan",
    "dog",
    "fin",
    "owl",
    "pair",
    "arch",
    "park",
    "room",
    "bolt",
    "land",
    "log",
    "load",
    "bar",
    "nest",
    "hero",
    "cord",
    "type",
    "site",
    "race",
    "seed",
    "pack",
    "hub",
    "meal",
    "pose",
    "leaf",
    "war",
    "fold",
    "tour",
    "role",
    "map",
    "cop",
    "bus",
    "bird",
    "line",
    "rack",
    "hunt",
    "task",
    "ton",
    "fig",
    "ring",
    "air",
    "bat",
    "pen",
    "diet",
    "mark",
    "lion",
    "crew",
    "cell",
    "form",
    "ray",
    "cap",
    "mom",
    "vote",
    "plug",
    "city",
    "tail",
    "wolf",
    "pit",
    "pan",
    "cart",
    "neck",
    "foot",
    "bag",
    "pine",
    "god",
    "bank",
    "rock",
    "sea",
    "lap",
    "pie",
    "mode",
    "cash",
    "arm",
    "wit",
    "gold",
    "ride",
    "surf",
    "mall",
    "deck",
    "hair",
    "note",
    "lock",
    "zone",
    "gift",
    "mate",
    "side",
    "gate",
    "week",
    "shop",
    "crop",
    "ice",
    "tube",
    "tree",
    "grid",
    "trap",
    "moon",
    "mine",
    "life",
    "lung",
    "wine",
    "tap",
    "wood",
    "poll",
    "card",
    "fire",
    "son",
    "tool",
    "inn",
    "file",
    "club",
    "sum",
    "pond",
    "soup",
    "hook",
    "face",
    "lip",
    "belt",
    "tip",
    "food",
    "boy",
    "sink",
    "core",
    "yard",
    "lamp",
    "pot",
    "mill",
    "ram",
    "rail",
    "boot",
    "tax",
    "dump",
    "song",
    "rage",
    "edge",
    "rent",
    "vice",
    "box",
    "hole",
    "girl",
    "loop",
    "weed",
    "show",
    "door",
    "test",
    "mail",
    "head",
    "bomb",
    "fuel",
    "fur",
    "car",
    "kit",
    "dish",
    "page",
    "link",
    "rush",
    "gas",
    "rose",
    "skin",
    "wrap",
    "rate",
    "stem",
    "fox",
    "pin",
    "heel",
    "cat",
    "turn",
    "pain",
    "lime",
    "van",
    "bike",
    "fact",
    "deal",
    "view",
    "pool",
    "well",
    "top",
    "tie",
    "row",
    "heap",
    "post",
    "user",
    "pole",
    "hawk",
    "slot",
    "host",
    "band",
    "wind",
    "hill",
    "game",
    "tank",
    "egg",
    "trim",
    "bell",
    "coin",
    "vet",
    "men",
    "rat",
    "coal",
    "day",
    "jar",
    "bean",
    "run",
    "text",
]


@dataclass
class GraphWalkConfig:
    """Configuration for a graph_walk task run.

    Attributes:
        graph_type: One of "grid", "ring", "hex", "cylinder".
        graph_size: Size parameter (m for m×m grid/hex, n for ring,
            n_ring for cylinder).
        graph_size_2: Second size parameter for cylinder (n_height).
        concepts: List of concept strings, one per graph node.
        context_length: Number of walk steps per sequence.
        nw: Window size for computing mean activations (last nw occurrences).
        separator: Token separator between concepts in the walk text.
        seed: Random seed for reproducibility.
    """

    graph_type: str
    graph_size: int
    graph_size_2: int | None = None
    concepts: list[str] = field(default_factory=list)
    context_length: int = 400
    nw: int = 50
    separator: str = "|"
    no_backtrack: bool = True
    seed: int = 42

    def __post_init__(self) -> None:
        valid_types = ("grid", "ring", "hex", "cylinder", "torus")
        if self.graph_type not in valid_types:
            raise ValueError(
                f"graph_type must be one of {valid_types}, got '{self.graph_type}'"
            )

        # Auto-fill graph_size_2 so it's always an int after construction.
        if self.graph_size_2 is None:
            if self.graph_type in ("cylinder", "torus"):
                raise ValueError(f"{self.graph_type} requires graph_size_2")
            self.graph_size_2 = self.graph_size

        if self.graph_type == "ring":
            expected_nodes = self.graph_size
        else:
            expected_nodes = self.graph_size * self.graph_size_2

        if not self.concepts:
            if expected_nodes > len(DEFAULT_CONCEPTS):
                raise ValueError(
                    f"Graph has {expected_nodes} nodes but only "
                    f"{len(DEFAULT_CONCEPTS)} default concepts available. "
                    f"Provide a custom concepts list."
                )
            self.concepts = DEFAULT_CONCEPTS[:expected_nodes]
        elif len(self.concepts) != expected_nodes:
            raise ValueError(
                f"Expected {expected_nodes} concepts for "
                f"{self.graph_type}({self.graph_size}), got {len(self.concepts)}"
            )
